### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### ISSUE THREAD

**Issue by velkrosmaak** [b0mbays/ha-cast#1]
I'm running this on a Ubuntu VM with python3 and python3.10 installed. I get this error when I try to run this script following the guide:#

`ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)`

This suggested to me that it had picked up python3.10, but in the hacast.service file python3 is referenced. Changed that to 3.10 and restarted the service but the error persisted. From the date of the recent commits it appears this is maintained and up to date (thank you by the way!) so i'm not sure what else to try. 

```
   Loaded: loaded (/etc/systemd/system/hacast.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2023-03-23 23:29:29 GMT; 3s ago
 Main PID: 3342 (python3)
    Tasks: 1 (limit: 2312)
   CGroup: /system.slice/hacast.service
           └─3342 /usr/bin/python3 /opt/ha-cast/ha-cast.py

Mar 23 23:29:29 orbit python3[3342]:     from .util.ssl_ import (
Mar 23 23:29:29 orbit python3[3342]:   File "/usr/lib/python3/dist-packages/urllib3/util/__init__.py", line 3, in <module>
Mar 23 23:29:29 orbit python3[3342]:     from .connection import is_connection_dropped
Mar 23 23:29:29 orbit python3[3342]:   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 3, in <module>
Mar 23 23:29:29 orbit python3[3342]:     from .wait import wait_for_read
Mar 23 23:29:29 orbit python3[3342]:   File "/usr/lib/python3/dist-packages/urllib3/util/wait.py", line 1, in <module>
Mar 23 23:29:29 orbit python3[3342]:     from .selectors import (
Mar 23 23:29:29 orbit python3[3342]:   File "/usr/lib/python3/dist-packages/urllib3/util/selectors.py", line 14, in <module>
Mar 23 23:29:29 orbit python3[3342]:     from collections import namedtuple, Mapping
Mar 23 23:29:29 orbit python3[3342]: ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by b0mbays** [comment]
Hey @velkrosmaak, sorry about that. It looks like i'm running Python 3.9.6 on my Pi that I was running this on! Downgrading to that would fix this, but I will try and put a fix out for Python 3.10.x soon.

I have a dependancy for Python 3.9 for some other scripts i'm running on my PI, could you try to update urllib3?

`pip3 install --upgrade urllib3`

I tried the script inside a python 3.10.6 and It was running fine too.. Strange!

I have since created a Home Assistant integration that uses the same code here, but doesn't rely on having to have an external linux box so you could also try this instead :) 

This is here: https://github.com/b0mbays/ha-continuously-casting-dashboard

**Comment by b0mbays** [comment]
Hi @velkrosmaak , do you need any more assistance with this? If you have moved over to the HACS integration I'll close this issue :)

**Comment by velkrosmaak** [comment]
Hey there! I have indeed moved over to the HACS integration setup so this
can be closed! Thanks for being on it! :)

**Comment by b0mbays** [comment]
Amazing! No problem. Let me know in the other project if you have any issues.
